network-store-iidm-tck/pom.xml, network-store-integration-test/pom.xml, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreToolsIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java, network-store-server/pom.xml, network-store-tools/pom.xml, pom.xml
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
**What is the current behavior?** *(You can also link to an open issue here)*
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
(if any of the questions/checkboxes don't apply, please delete them entirely)
=> Migrate to PowSyBl WS 2.1.0

network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/ActivePowerLimitsIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/AliasesIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/ApparentPowerLimitsIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/ActivePowerControlIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/CoordinatedReactivePowerControlIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/DiscreteMeasurementsIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/HvdcAngleDroopActivePowerIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/HvdcOperatorActivePowerRangeIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/LoadDetailIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/MeasurementsIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/RemoveReactivePowerControlIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/SlackTerminalIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/ThreeWindingsTransformerPhaseAngleClockIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/TwoWindingsTransformerPhaseAngleClockIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/extensions/VoltagePerReactivePowerControlIT.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/util/NodeBreakerTopologyIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java, pom.xml
Update to powsybl-parent-ws 10
=> Upgrade to powsybl-parent-ws 10

network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreToolsIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java, network-store-server/pom.xml, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreApplication.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/java/com/powsybl/network/store/server/exceptions/RestResponseEntityExceptionHandler.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java, pom.xml
=> springboot 3.2

network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStorageTestCaseFactory.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java, network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java, network-store-server/src/main/resources/db/changelog/changesets/changelog_20231026T120000Z.xml, network-store-server/src/main/resources/db/changelog/db.changelog-master.yaml, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java, network-store-tools/pom.xml, pom.xml
=> powsybl ws dependencies 2.5.0

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreApplication.java, pom.xml
=> update to powsybl-ws-dependencies 2.6.0

network-store-server/src/main/java/com/powsybl/network/store/server/QueryCatalog.java
=> Add orderby index_column to tapchangerSteps select query

network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreExtensionsIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/TestUtils.java
Move extensions test to separate class for better readability
=> Move extensions tests to separate test class

pom.xml
Override network store with patched version 1.11.1
=> Override network store with patched version 1.11.1

network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java
Enable test after the fix https://github.com/powsybl/powsybl-network-store/pull/394. 
To merge when https://github.com/powsybl/powsybl-network-store/pull/394 is released.
=> Enable assert after fix in network-store

network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreExtensionsIT.java
Add integration tests for the new extensions added: line position and substation position
=> Add intergration tests for substation position and line position

network-store-server/pom.xml
Dependent of powsybl/powsybl-ws-commons#49
=> Enable Prometheus in every microservice

network-store-iidm-tck/src/test/java/com/powsybl/network/store/client/NetworkFactoryTestService.java, network-store-iidm-tck/src/test/java/com/powsybl/network/store/tck/GroundIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreToolsIT.java, network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreValidationTest.java, network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java, network-store-server/src/main/resources/db/changelog/changesets/changelog_20240701T114700Z.xml, network-store-server/src/main/resources/db/changelog/db.changelog-master.yaml, pom.xml
Update to powsybl/powsybl-ws-dependencies#44
=> Upgrade to powsybl-dependencies 2024.2.0

network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/java/com/powsybl/network/store/server/QueryCatalog.java, network-store-server/src/main/resources/db/changelog/changesets/changelog_20220928T213000Z.xml, network-store-server/src/main/resources/db/changelog/changesets/changelog_20240808T110000Z.xml, network-store-server/src/main/resources/db/changelog/changesets/regulationPoint_20240808T110000Z.sql, network-store-server/src/main/resources/db/changelog/db.changelog-master.yaml, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java, pom.xml
linked to https://github.com/powsybl/powsybl-network-store/pull/424
=> add regulation point for svc, shunts, vsc and generators

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
=> fix requests on regulation points

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
=> Fix regulation points again

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
=> fix regulation pont for shunt compensator

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java, pom.xml
=> upgrade network store server to v1.17.1

network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java
=> add missing function for regulation point for identifiable getter

network-store-integration-test/pom.xml, network-store-server/pom.xml, pom.xml
=> Springboot 3.3.3 migration

network-store-server/src/main/resources/db/changelog/changesets/changelog_20240924T110000Z.xml, network-store-server/src/main/resources/db/changelog/changesets/fix_regulationPoint_20240924T110000Z.sql, network-store-server/src/main/resources/db/changelog/db.changelog-master.yaml
=> fix regulation mode column to remove quote

network-store-server/src/main/resources/db/changelog/changesets/changelog_20241011T120000Z.xml, network-store-server/src/main/resources/db/changelog/db.changelog-master.yaml, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java
Cleanup after https://github.com/powsybl/powsybl-network-store-server/pull/32
=> Cleanup columns that were used before generalized extensions

network-store-iidm-tck/pom.xml, network-store-integration-test/pom.xml, network-store-server/pom.xml, network-store-tools/pom.xml, pom.xml
NO
chore
version 1.0.0-SNAPSHOT
version 2.9.0-SNAPSHOT
The automated github release process failed because of a branch protection on this repo only, manually doing the same commit
=> Update SNAPSHOT version to v2.9.0

network-store-server/src/main/resources/db/changelog/changesets/changelog_20241031T110000Z.xml
=> fix migration script

network-store-integration-test/src/test/java/com/powsybl/network/store/integration/NetworkStoreIT.java, network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/java/com/powsybl/network/store/server/QueryCatalog.java, network-store-server/src/main/resources/db/changelog/changesets/changelog_20241204T110000Z.xml, network-store-server/src/main/resources/db/changelog/changesets/move_regulating_to_regulationPoint_20241204T110000Z.sql, network-store-server/src/main/resources/db/changelog/db.changelog-master.yaml, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreRepositoryTest.java, pom.xml
Depends on powsybl/powsybl-ws-dependencies#63
=> Upgrade to powsybl ws dependencies 2.17.0

network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreRepositoryTest.java
No
Fix the test testRegulatingPointForThreeWindingsTransformers failing once every 2 or 3 times.
=> Fix unstable tests for regulating point

network-store-server/src/main/java/com/powsybl/network/store/server/migration/v214tapchangersteps/V214TapChangerStepsQueryCatalog.java
=> fix v214 steps migration

network-store-server/src/main/java/com/powsybl/network/store/server/migration/v211limits/V211LimitsQueryCatalog.java, network-store-server/src/main/java/com/powsybl/network/store/server/migration/v214tapchangersteps/V214TapChangerStepsQueryCatalog.java
=> remove useless methods

network-store-server/pom.xml, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreObserver.java
No
Add metrics on get, remove, update, clone with micrometer API
=> Add metrics on get, remove, update, clone

network-store-server/src/main/java/com/powsybl/network/store/server/ExtensionHandler.java, network-store-server/src/main/java/com/powsybl/network/store/server/LimitsHandler.java, network-store-server/src/main/java/com/powsybl/network/store/server/Mappings.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreController.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/java/com/powsybl/network/store/server/QueryCatalog.java, network-store-server/src/main/java/com/powsybl/network/store/server/Utils.java, network-store-server/src/main/java/com/powsybl/network/store/server/migration/v211limits/V211LimitsMigration.java, network-store-server/src/main/java/com/powsybl/network/store/server/migration/v214tapchangersteps/V214TapChangerStepsMigration.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreControllerIT.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreRepositoryPartialVariantExternalAttributesTest.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreRepositoryPartialVariantIdentifiablesTest.java, network-store-server/src/test/java/com/powsybl/network/store/server/NetworkStoreRepositoryTest.java, network-store-server/src/test/java/com/powsybl/network/store/server/V214TapChangerStepMigrationTest.java, network-store-server/src/test/resources/OneOperationalLimitsGroupResultTest.json, network-store-server/src/test/resources/allOperationalLimitsGroupForBranchLine1ResultTest.json, network-store-server/src/test/resources/allOperationalLimitsGroupResultTest.json, network-store-server/src/test/resources/allSelectedOperationalLimitsGroupResultTest.json, pom.xml
This reverts commit 6b8a18d350d7ec5c5f33ef0205f52d9acbc57da9.
=> restore lazy loading and upgrade network store to v1.28.0

network-store-server/src/main/java/com/powsybl/network/store/server/LimitsHandler.java, network-store-server/src/main/java/com/powsybl/network/store/server/NetworkStoreRepository.java, network-store-server/src/main/java/com/powsybl/network/store/server/QueryCatalog.java, network-store-server/src/main/java/com/powsybl/network/store/server/QueryLimitsCatalog.java
non
refactoring
add all queries related to limits in a separated file and correct a method
=> refactoring of limits handler

.github/workflows/dockerdeploy.yml
NO
add a manual docker deploy worfklow
no 
no useable workflow for releases
see https://github.com/powsybl/github-ci/pull/59
=> Add dockerdeploy worfklow for manual releases

network-store-iidm-tck/pom.xml, network-store-integration-test/pom.xml, network-store-server/pom.xml, network-store-tools/pom.xml, pom.xml
=> Release v2.24.0

network-store-iidm-tck/pom.xml, network-store-integration-test/pom.xml, network-store-server/pom.xml, network-store-tools/pom.xml, pom.xml
=> Next Release v2.25.0 snapshot
